AWSTemplateFormatVersion: '2010-09-09'
Description: Template for deploying the frontend component required by muphone-frontend

Resources:
    HostingBucket:
        Type: 'AWS::S3::Bucket'
        Properties:
            WebsiteConfiguration:
                IndexDocument: 'index.html'

    HostingBucketResourcePolicy:
        Type: 'AWS::S3::BucketPolicy'
        Properties:
            Bucket: !Ref HostingBucket
            PolicyDocument:
                Statement:
                    - Action:
                        - "s3:GetObject"
                      Effect: "Allow"
                      Resource:
                          Fn::Join:
                              - ""
                              - 
                                - "arn:aws:s3:::"
                                - !Ref HostingBucket
                                - "/*"
                      Principal: "*"


Outputs:
    ApplicationUrl:
        Description: URL of the application
        Value: !GetAtt HostingBucket.WebsiteURL
    HostingBucketName:
        Description: Name of the bucket where you have to deploy your static build
        Value: !Ref HostingBucket


